services:
  database:
    image: ghcr.io/robinbezak-cz/database-service:latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      # This is required by the base MSSQL image
      ACCEPT_EULA: "Y"